This notebook will cover various aspects of deep learning, down to the implementation level.

# Neural Network Vectorized

## Introduction

In this part, we will see the implementation of a neural network using _python_. Mind you, this will be vectorized, and thus will be the fastest possible _semi-vanilla_ implementation. As usual, we begin by importing the basic modules.

In [1]:
import numpy as np
try:
    import sklearn.svm as svm
except:
    print("No Sklearn")
try:
    import matplotlib.pyplot as plt
except:
    print("No matplotlib")
from importlib import reload

In order to vectorize our implementations, we need our data to be stacked as x(i).T elements. That is given an m x n dataset, we should model X as X.T

In [15]:
raw_data = np.random.rand(1000, 3)
y = ( np.random.rand(raw_data.shape[0], 1) >= 0.5).astype(int)
print("Raw", raw_data.shape, raw_data,"Y", y.shape, y.T, sep = "\n")
X = raw_data.T

Raw
(1000, 3)
[[ 0.23780701  0.81975135  0.54089564]
 [ 0.03795871  0.66373952  0.63443336]
 [ 0.92047963  0.96074888  0.0227337 ]
 ..., 
 [ 0.33846518  0.26662632  0.17106735]
 [ 0.93018299  0.13062804  0.8267541 ]
 [ 0.65745262  0.50802517  0.02585104]]
Y
(1000, 1)
[[0 1 0 1 1 1 1 1 0 1 1 0 1 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 1 1
  1 1 0 0 1 1 0 0 1 1 0 0 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 1 1 0 1 1 1 0 0 0 1
  1 0 1 0 0 0 1 0 1 0 1 0 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 1 0 0
  0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 1 0 1 0 1 1 0 1 1
  1 0 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 1 0 1 0 1 1 1 1 0 0 1 0 0 1 1
  0 0 1 0 0 0 0 1 1 1 1 1 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 1 1 0 0
  1 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 1 1
  1 1 1 0 1 0 1 1 0 1 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 0 1 1 0 1 1 1 1
  0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 0 0 1 1 1 0
  0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 

Here, the ith column of the X matrix will correspond to the ith row of the y matrix. 

In [18]:
print(X.shape, y.shape)
assert(X.shape[-1] == y.shape[0])

(3, 1000) (1000, 1)


Now, let us implement a basic neural network with one hidden layer. To vectorize, we have a weights matrix, W[1], that will be of the shape nodes * row(X). similarly W[2] = output_node * row(W[1])

In [24]:
W_1 = np.random.rand(3, X.shape[0])
b_1 = np.random.rand(W_1.shape[0], 1)
W_2 = np.random.rand(1, W_1.shape[0])
b_2 = np.random.rand(W_2.shape[0], 1)
print(W_1, b_1, W_2, b_2, sep = "\n")

[[ 0.59547179  0.56816325  0.56929769]
 [ 0.78406036  0.14691009  0.07514067]
 [ 0.14671081  0.57953744  0.05681349]]
[[ 0.47057353]
 [ 0.43558697]
 [ 0.37172815]]
[[ 0.46026517  0.82765648  0.17095731]]
[[ 0.45059382]]


Now that we have the weights in place, we can perform the forward propogation as follows

In [55]:
Z_1 = np.dot(W_1, X) + b_1

class Activations:
    def sig(z):
        return 1 / (1 + np.exp(-z))
    def tanh(z):
        return np.tanh(z)

def a_func(z, func = sig):
    return func(z)

a_func = np.vectorize(a_func)
A_1 = a_func(Z_1, tanh)
Z_2 = np.dot(W_2, A_1) + b_2
A_2 = a_func(Z_2, tanh)
A_2.T - y

array([[ 0.90901801],
       [-0.11408978],
       [ 0.93799393],
       [-0.06850724],
       [-0.0825949 ],
       [-0.09489825],
       [-0.09601676],
       [-0.11457331],
       [ 0.88406732],
       [-0.09155267],
       [-0.07387031],
       [ 0.91636026],
       [-0.09430645],
       [-0.06667483],
       [ 0.93473887],
       [ 0.90369757],
       [ 0.92785975],
       [-0.11684135],
       [ 0.91226335],
       [-0.0753513 ],
       [ 0.91675182],
       [ 0.88150373],
       [ 0.92379391],
       [ 0.79251965],
       [ 0.89260598],
       [ 0.93455607],
       [-0.06887139],
       [ 0.90464686],
       [-0.08853419],
       [-0.07772079],
       [ 0.90484353],
       [ 0.91713291],
       [ 0.89998564],
       [ 0.90851321],
       [-0.08304609],
       [-0.10673691],
       [-0.07505875],
       [-0.07485291],
       [-0.07384237],
       [ 0.90175081],
       [ 0.90555538],
       [-0.10373744],
       [-0.12323853],
       [ 0.93890376],
       [ 0.8952435 ],
       [-0

In [34]:
np.dot(W_1, X).shape

(3, 1000)